# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Properties(object):
    def setupUi(self, Properties):
        Properties.setObjectName("Properties")
        Properties.resize(480, 520)
        Properties.setMinimumSize(QtCore.QSize(480, 520))
        Properties.setMaximumSize(QtCore.QSize(480, 520))
        Properties.setSizeIncrement(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(Properties)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(32, 22, 136, 35))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(31, 69, 160, 35))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(31, 192, 164, 35))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(31, 277, 176, 35))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.slideFilter = QtWidgets.QSlider(self.centralwidget)
        self.slideFilter.setGeometry(QtCore.QRect(180, 321, 270, 22))
        self.slideFilter.setSizeIncrement(QtCore.QSize(3, 0))
        self.slideFilter.setOrientation(QtCore.Qt.Horizontal)
        self.slideFilter.setObjectName("slideFilter")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(51, 320, 109, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setScaledContents(False)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(51, 113, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setScaledContents(False)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(51, 150, 115, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setScaledContents(False)
        self.label_8.setObjectName("label_8")
        self.spinBlurVal = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBlurVal.setGeometry(QtCore.QRect(180, 150, 270, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.spinBlurVal.setFont(font)
        self.spinBlurVal.setObjectName("spinBlurVal")
        self.spinKcluster = QtWidgets.QSpinBox(self.centralwidget)
        self.spinKcluster.setGeometry(QtCore.QRect(180, 235, 270, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.spinKcluster.setFont(font)
        self.spinKcluster.setObjectName("spinKcluster")
        self.txtSigma = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSigma.setGeometry(QtCore.QRect(179, 360, 270, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtSigma.setFont(font)
        self.txtSigma.setObjectName("txtSigma")
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setGeometry(QtCore.QRect(270, 420, 167, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnSave.setFont(font)
        self.btnSave.setObjectName("btnSave")
        self.btnPreview = QtWidgets.QPushButton(self.centralwidget)
        self.btnPreview.setGeometry(QtCore.QRect(50, 420, 176, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnPreview.setFont(font)
        self.btnPreview.setObjectName("btnPreview")
        self.txtImgFile = QtWidgets.QLineEdit(self.centralwidget)
        self.txtImgFile.setGeometry(QtCore.QRect(174, 23, 240, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtImgFile.setFont(font)
        self.txtImgFile.setObjectName("txtImgFile")
        self.btnBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.btnBrowse.setGeometry(QtCore.QRect(420, 22, 31, 31))
        self.btnBrowse.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Download - HDD/opened-folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBrowse.setIcon(icon)
        self.btnBrowse.setFlat(True)
        self.btnBrowse.setObjectName("btnBrowse")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(50, 360, 135, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setScaledContents(False)
        self.label_9.setObjectName("label_9")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(51, 235, 126, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setScaledContents(False)
        self.label_6.setObjectName("label_6")
        self.spinLineSize = QtWidgets.QSpinBox(self.centralwidget)
        self.spinLineSize.setGeometry(QtCore.QRect(180, 110, 270, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.spinLineSize.setFont(font)
        self.spinLineSize.setObjectName("spinLineSize")
        Properties.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Properties)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        Properties.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Properties)
        self.statusbar.setObjectName("statusbar")
        Properties.setStatusBar(self.statusbar)

        self.retranslateUi(Properties)
        QtCore.QMetaObject.connectSlotsByName(Properties)

    def retranslateUi(self, Properties):
        _translate = QtCore.QCoreApplication.translate
        Properties.setWindowTitle(_translate("Properties", "MainWindow"))
        self.label.setText(_translate("Properties", "Image file : "))
        self.label_2.setText(_translate("Properties", "Edge setting : "))
        self.label_3.setText(_translate("Properties", "Color setting : "))
        self.label_4.setText(_translate("Properties", "Noise filtering : "))
        self.label_5.setText(_translate("Properties", "Filter size : "))
        self.label_7.setText(_translate("Properties", "Line size : "))
        self.label_8.setText(_translate("Properties", "Blur value : "))
        self.btnSave.setText(_translate("Properties", "Save image"))
        self.btnPreview.setText(_translate("Properties", "Generate Preview"))
        self.label_9.setText(_translate("Properties", "Sigma value : "))
        self.label_6.setText(_translate("Properties", "K - clusters : "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Properties = QtWidgets.QMainWindow()
    ui = Ui_Properties()
    ui.setupUi(Properties)
    Properties.show()
    sys.exit(app.exec_())

